version: "3.5"
services:
  database:
    image: mysql:8.1
    volumes:
      - ./docker/database/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      DB_HOST: "database"
    depends_on:
      database:
        condition: service_healthy